print("Pokemon Damage Calculator")
targt = float(1)
weathr = float(1)
badge = float(1)
critic = float(1)
randm = float(1)
stabi = float(1.5)
typ = float(0.5)
burn = float(1)
other = float(1)
modifier = float(targt*weathr*badge*critic*randm*stabi*typ*burn*other)
lvl = int(90)
pwr = int(110)
attack = int(205)
dfs = int(188)
dmg = float(((((2*lvl/5)+2)*pwr*(attack/dfs)/50)+2)*modifier)
print("\nAnswer: "+str(dmg))